### ISSUE TITLE
Feature request: keep dirvish buffers out of the jumplist

### ISSUE THREAD

**Issue by rlue** [justinmk/vim-dirvish#110]
Oftentimes, after using dirvish to navigate from one buffer to another, I'll use `<C-o>` to jump back to the original buffer. But since the dirvish navigation buffer gets added to the jumplist, I actually have to hit `<C-o>` twice.

What would @justinmk think of adding a config option (_e.g.,_ `g:dirvish_no_jump`) to keep dirvish buffers off of the jumplist altogether? I'd be willing to take a stab at a PR, if you're open to it.

**Comment by justinmk** [comment]
No, this is out of scope. 

In fact that used to how dirvish behaved, then it was requested to add to the jumplist.  

Also it's difficult or impossible to reliably implement the behavior you are asking for, because vim's `:keepjumps` doesn't always work.

I used to care about this feature but I learned to accept it. Buffers are buffers. If you try to convince vim that a buffer is not a buffer you'll have a bad time :)
