### ISSUE TITLE
Is there a way to hide files in .gitignore?

### ISSUE THREAD

**Issue by alex-miura** [justinmk/vim-dirvish#125]
Is there a way to hide files in .gitignore? I was looking at `dirvish_mode` and it seemed like it could be possible.

**Comment by justinmk** [comment]
> I was looking at dirvish_mode and it seemed like it could be possible.

Yes.  `:help g:dirvish_mode` notes that it defaults to `1`, which means:

    'suffixes' and 'wildignore' determine sorting and visibility

So you could set wildignore to some expression that is equivalent to your `.gitignore` stuff. Although, I don't recommend that, because 'wildignore' is a very heavy-handed way to ignore things in Vim.

You could do something like this:

    let g:dirvish_mode = ':call DeleteGitignoredLines()'

Dirvish isn't going to add native support for parsing `.gitignore`, that's wildly out of scope.
