### ISSUE TITLE
g:dirvish_mode won't work if g:dirvish_relative_paths = 1

### ISSUE THREAD

**Issue by zealotrush** [justinmk/vim-dirvish#153]
Here is a simple way to reproduce this issue.

1. Prepare a test folder as below.

```
tree -a .
.
├── .hidden
├── bar
├── folder-a
├── folder-b
└── foo

2 directories, 3 files
```

2. In `$MYVIMRC` file, add these settings:

```viml
let g:dirvish_mode = ':sort ,^.*[\/],'
let g:dirvish_relative_paths = 0
```

3. Open vim, press `-` to open Dirvish. It can be seen that folders are displayed first, which means the `g:dirvish_mode` settings is effective.

```
folder-a/
folder-b/
.hidden
bar
foo
```

4. Change `g:dirvish_relative_paths` to 1. Repeat step 3. Folders are no longer displayed first.

```
bar
folder-a/
folder-b/
foo
.hidden
```

By saying vim, I'm actually referring to Neovim v0.4.3.

Is this a bug, or it's just I missed something?

**Comment by justinmk** [comment]
Did you try navigating to another directory?  It should work for all directories _except_ "current directory" (`:pwd`). Because

    :sort ,^.*[\/],

depends on at least one slash (/) existing in each buffer line. With relative paths some lines may not have slashes. See also `:help :sort`. 

This works instead:

    :%sort ,^\v(.*[\/])|\ze,

More discussion in https://github.com/justinmk/vim-dirvish/issues/89 .

**Comment by zealotrush** [comment]
It worked. Thanks!

But now I cannot hide hidden files in Dirvish buffer with `g:dirvish_relative_paths = 1`. Here is my dirvish config:

```viml
let g:dirvish_mode =
      \ ':sort ,^\v(.*[\/])|\ze, | silent keeppatterns g@\v/\.[^\/]+/?$@d _'
let g:dirvish_relative_paths = 1
```

The regex is a little bit obscure to me. Could you please help me?
