### ISSUE TITLE
Why not s and v for opening in splits and vsplits

### ISSUE THREAD

**Issue by nomasprime** [justinmk/vim-dirvish#162]
I've remapped o and a to s and v because I think it's more intuitive and Vim-like.

Would just like to know why not use these in the first place and the motivation behind o and a?

Thanks for a great plug-in. Tried a few and keep coming back.

**Comment by justinmk** [comment]
they're actually not intuitive if you compare the typical semantics in Vim itself. 

- v is visual mode. besides the fact that visual-mode is a legitimate thing to use in a Dirvish buffer (and thus it's obnoxious that netrw maps over it), it also is semantically unrelated to "vertical split". (`ctrl-w v` already works in Dirvish so that doesn't count.)
- `o` in normal-mode opens a line , so it is a reasonable mnemonic for "horizontal". 
   - this is also what vim-vinegar and netrw already use for that purpose.
-`a` in normal-mode has a vaguely vertical behavior compared to `o`, and it's not useful in a Dirvish buffer, so it is a reasonable choice.
    - it also has a nice duality with `i`

**Comment by nomasprime** [comment]
Thought it must be something like this.

The parallel seems as tenuous as `s` and `v` but at least it doesn't clobber anything. Maybe `gs` and `gv` are a better compromise?

Having said that I'm not sure why you'd use `v` in Dirvish instead of `V`?

Also how do you use Sneak in Dirvish, instead of going to line?
