### ISSUE TITLE
Reduce filename to be relative to current directory when opening file(s)

### ISSUE THREAD

**Issue by bfrg** [justinmk/vim-dirvish#170]
Currently, file names always have a full path, even when a file below the current working directory is opened with dirvish. With `fnamemodify(path, ':.')` Vim will try to reduce the file name to be relative to the current working directory. This looks a lot smoother in the statusline and under `:ls`.

Please consider keeping the file names as short as possible.

The following patch seems to work:
```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index d600e36..a0ed400 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -256,9 +256,9 @@ function! s:open_selected(splitcmd, bg, line1, line2) abort
     endif
 
     if isdirectory(path)
-      exe (p || a:splitcmd ==# 'edit' ? '' : a:splitcmd.'|') 'Dirvish' fnameescape(path)
+      exe (p || a:splitcmd ==# 'edit' ? '' : a:splitcmd.'|') 'Dirvish' fnameescape(fnamemodify(path, ':.'))
     else
-      exe (p ? 'edit' : a:splitcmd) fnameescape(path)
+      exe (p ? 'edit' : a:splitcmd) fnameescape(fnamemodify(path, ':.'))
     endif
 
     " Return to previous window after _each_ split, else we get lost.
```

**Comment by justinmk** [comment]
Full paths are forced to avoid duplicate buffers, so that existing buffer can be unambiguously found via `bufnr()` et al. IIRC on Windows/gVim this was a problem. There are some comments in the source code about it. 

Avoiding "duplicate" buffers (i.e. two different buffers showing the same logical directory) is important for navigation, remembering cursor position, probably other stuff I'm forgetting.

But maybe it's worth trying again.

**Comment by gosukiwi** [comment]
Could this maybe be an option? I use CtrlP for finding files and it opens them with relative path, and now I end up with mixed paths, which is not that big of an issue but I'd rather make things consistent, and I prefer relative paths 😅

**Comment by justinmk** [comment]
Fixed by https://github.com/justinmk/vim-dirvish/commit/2fc45512f58eb778f3db3e38c215ac38ff8bb5c2

Please let me know if there are regressions.
