### ISSUE TITLE
Can't open file with literal backslash in the name

### ISSUE THREAD

**Issue by wincent** [justinmk/vim-dirvish#173]
I don't usually have files with literal backslashes in their names, but I just stumbled on one that I had created by accident and Dirvish cannot open it.

## To repro

1. `touch 'foo\ bar\ baz'`
2. Open Vim and inspect directory with Dirvish (ie. `vim .`)
3. Hit `<CR>` to open `foo\ bar\ baz`.

### Expected

File opens.

### Actual

Error:

```
dirvish: invalid (access denied?): /private/var/folders/tl/04jnvr4s34v704k5h2rqjmkh0000gn
/T/tmp.tHZmF5RG/foo/ bar/ baz
```

### Notes

Not specific to Vim; happens in Neovim too.

**Comment by lacygoill** [comment]
The message comes [from here](https://github.com/justinmk/vim-dirvish/blob/0a53fadc22ab6df6aed9cc580c9e498715870522/autoload/dirvish.vim#L250).
It's caused by the previous evaluation of [`s:sl()`](https://github.com/justinmk/vim-dirvish/blob/0a53fadc22ab6df6aed9cc580c9e498715870522/autoload/dirvish.vim#L17-L19) which translates the backslashes into slashes.
Apparently, it was needed to fix [a bug on Windows](https://github.com/justinmk/vim-dirvish/issues/37).

A possible (and naive?) fix would be to limit the translation to Windows:

```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index d600e36..cc94e20 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -15,7 +15,7 @@ endfunction
 
 " Normalize slashes for safe use of fnameescape(), isdirectory(). Vim bug #541.
 function! s:sl(path) abort
-  return tr(a:path, '\', '/')
+  return has('win32') ? tr(a:path, '\', '/') : a:path
 endfunction
 
 function! s:normalize_dir(dir, silent) abort
```

**Comment by justinmk** [comment]
@lacygoill that should be fine, would you mind sending a PR
