### ISSUE TITLE
Alternate buffer not being set correctly

### ISSUE THREAD

**Issue by Asheq** [justinmk/vim-dirvish#183]
I'm running into situations where the alternate file is not what I expect, which
makes using `C-^` very disorienting. Here are two distinct scenarios where this
occurs:

## Pre setup
1. Create a directory with `file-A`, `file-B`, and `file-C`
1. `nvim` in that directory

## Scenario 1
1. `:e file-A`
1. `:e file-B` (making `file-A` the alternate file)
1. `:Dirvish` or `-`
1. `gq`

**Problem**: After `gq`, the alternate file should still be `file-A` -- instead
it is the dirvish buffer.  Strangely, if you open dirvish again and `gq` again,
the alternate file _does_ become `file-A` this time.

## Scenario 2
1. `-`, then `i` on `file-A`
1. `-`, then `i` on `file-B` (making `file-A` the alternate file)
1. In `file-B`, insert a `.` character (save file) and then press `gf` on the
   `.` to open dirvish in the current directory
1. `i` on `file-C`

**Problem**: After `i` on `file-C`, `file-B` should be the alternate file --
instead it is `file-A`.

---
PS: Thanks for one of the best vim plugins ever :) BTW, [here](https://www.youtube.com/watch?v=ILpdtL-4gv0) is a recent
video I came across about how fast dirvish is compared to the others.

**Comment by beardedsakimonkey** [comment]
Dug into this a bit and I think I understand the issues, but not yet sure of the solution.
### Scenario 1
in step 3, dirvish will recurively call `dirvish#open()` because [this `:edit`](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/autoload/dirvish.vim#L429) triggers [BufEnter](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/plugin/dirvish.vim#L19-L21).  This `:edit` takes us to a new buffer, **updating vim's alternate buffer**.  So in that `autocmd`, we're in a brand new buffer, which does not have `b:dirvish`, so we `exe 'Dirvish %'`, recursing back into `dirvish#open()`.  But since we now have a different `bufnr('#')`, `s:save_state()` clobbers the correct altbuf with the new altbuf which is the same as prevbuf.

So at this point, we're in this state:
```
:ls!
  1  h   "file-A"                       line 1
  2 #h   "file-B"                       line 1
  3u%a   "/Users/tim/test/"             line 3

:echo w:dirvish.altbuf w:dirvish.prevbuf
2 2
```
From this point, when we `gq` out of dirvish, we [visit buf 2](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/autoload/dirvish.vim#L225), but [this second visit fails](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/autoload/dirvish.vim#L226) because [`prevbuf == bufnr('%')`](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/autoload/dirvish.vim#L282). So, we're left with the dirvish buffer as our altbuf.

My initial solution is to `noau` the `:edit` to avoid the recursive call that clobbers `w:dirvish.altbuf`:
```diff
diff --git a/autoload/dirvish.vim b/autoload/dirvish.vim
index 4fd26a2..1bdc385 100644
--- a/autoload/dirvish.vim
+++ b/autoload/dirvish.vim
@@ -426,7 +426,7 @@ function! s:open_dir(d, reload) abort
   endfor

   if -1 == bnr
-    execute 'silent' s:noswapfile 'edit' fnameescape(d._dir)
+    execute 'silent noau' s:noswapfile 'edit' fnameescape(d._dir)
   else
     execute 'silent' s:noswapfile 'buffer' bnr
   endif
```

I'll try this out for a bit to see if it causes issues.

### Scenario 2
Unfortunately, I don't think this is fixable.  As pointed out in [this comment](https://github.com/justinmk/vim-dirvish/blob/7c4dc5945b15a6b97ebef860070d30e36da01788/autoload/dirvish.vim#L185), we cannot get the altbuf when opening dirvish via `:edit` (`gf` uses `:edit` under the hood).  This is because dirvish "hooks into" `:edit` via the `BufEnter` autocmd, but at that point, we're in a new buffer, and cannot access the altbuffer's altbuffer (easily, at least).

**Comment by justinmk** [comment]
@beardedsakimonkey thanks for your analysis. unfortunately using `:noau` regresses 61282f2453af78c30f4e40428d43099c8b30a428 .
