### ISSUE TITLE
Opening file from :Gstatus with Dirvish buffer active opens file in odd place

### ISSUE THREAD

**Issue by dbatten5** [justinmk/vim-dirvish#202]
Normally, if I have an active buffer and open the fugitive summary window with `:Gstatus` and press enter on a file with changes, it replaces the active buffer with the file under the cursor. However, when I have a Dirvish buffer open and do the same thing, it opens the file in a new horizontal split underneath my fugitive window. Is there to force Dirvish to behave the same as other filetypes in this respect?

**Comment by idbrii** [comment]
It's because dirvish buffers are buftype=nofile. See [s:UsableWin in fugitive](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L4421-L4426).

It wouldn't make sense for dirvish to stop using nofile (since its buffers don't represent a file), so you'd have to ask for fugitive to support replacing nofile. See tpope/vim-fugitive@6faf165e for the reason why nofile was initial introduced.
