### ISSUE TITLE
Seemingly no way to override default key mappings

### ISSUE THREAD

**Issue by jmcantrell** [justinmk/vim-dirvish#207]
Given that the user's `ftplugin`s are loaded after a package's, wouldn't that make checks like the following pointless?

https://github.com/justinmk/vim-dirvish/blob/master/ftplugin/dirvish.vim#L9

Some backstory. I currently have a global mapping on `q`, which dirvish maps to a deprecation warning. It overrides my mapping, so I decided to add a mapping to `<plug>(dirvish_quit)` in `~/.vim/ftplugin/dirvish.vim` so that dirvish would see that mapping and skip adding the deprecation warning.

Because of the previously mentioned loading order of `ftplugin`s, it seems like it's impossible for the user to make any `<plug>` mappings for dirvish.

Wouldn't it be better to put these default mappings in `after/ftplugin`?

**Comment by justinmk** [comment]
> Wouldn't it be better to put these default mappings in `after/ftplugin`?

`after/` must not be used by plugins, it is for users so that they can override plugins.

> I currently have a global mapping on `q`, which dirvish maps to a deprecation warning. It overrides my mapping, so I decided to add a mapping to `<plug>(dirvish_quit)` in `~/.vim/ftplugin/dirvish.vim` so that dirvish would see that mapping and skip adding the deprecation warning.

It works for me. It depends the order of directories listed in your 'runtimepath' : 

    :set runtimepath?

If you don't want to fiddle with rearranging your runtimepath (most likely you're using a plugin manager which does that for you), you can user `after/`, i.e. put your custom settings in ~/.vim/**after**/ftplugin/dirvish.vim
