### ISSUE TITLE
Buf{something} autocommand isn't always run

### ISSUE THREAD

**Issue by Carpetsmoker** [justinmk/vim-dirvish#23]
When I do: `vim .` the `BufCreate` autocommand isn't executed, but if I do `vim -c ':e .'` it is.

I see a lot of `noau` in the script; I'm not sure why you would ever need that? If I understand the intention of this plugin correct, it's designed to be "just a buffer", so stuff like running autocommands seems to be a part of that to me?

At any rate, both methods (`vim .` and `:e .`) should probably do the _same_.

**Comment by justinmk** [comment]
noau is to avoid triggering autocmds while forcing the alternate buffer. Though this can be avoided in Vim 7.4.7xx.

Does BufCreate work in the way you expect for non-dirvish buffers?

**Comment by justinmk** [comment]
In the cases you mentioned, Vim creates the buffer _before_ Dirvish ever sees it. Any autocmd you set up won't get triggered in the `vim .` case. Can be verified by adding `au BufCreate * echom localtime()` in vimrc and then compare `vim foo` to `vim -c 'e foo'`, where `foo` is a non-existent file.

Note that `:h BufCreate` says it's for when a buffer is added to the buffer list. But dirvish buffers are 'nobuflisted', which I would think is generally preferable. 

Regarding `noau`: it's in `s:do_open` to avoid infinite loop, though that's avoidable in other ways. The other `noau` are mostly when tickling the alternate buffer, and those cases could be avoided in Vim 7.4.7xx.

**Comment by Carpetsmoker** [comment]
Right. I picked the wrong example with `BufCreate` as I as I misremembered the subtle differences between the various autocmds :-/  I would expect *some* auto autocommand to be run; `BufRead*`? This can still be done manually with `doautocmd` btw.

The problem is that one of my plugins wants to create a `b:` variable for every buffer. I can use `BufEnter`, but that gets run *every time* a buffer is entered, so it's not exactly ideal...

**Comment by justinmk** [comment]
> This can still be done manually with doautocmd btw.

Yep, that's what I will do if removing noau judiciously is unfeasible.

**Comment by justinmk** [comment]
Documentation of `BufRead[Post]` mentions that it will not be triggered for `buftype=nofile` ("Not used when the file doesn't exist"). 

After removing all cases of `:noau`, `BufNew` works for `:edit <nothing>` and `:edit <directory>`. But it never works for `:Dirvish ...` (nor do `BufAdd`, `BufNewFile`, `BufReadPost`, and `BufFilePost`, for _either_ case). 

So `:noau` doesn't seem to be the root cause of this problem. Vim considers directory-like paths an "error" (which is a Vim bug, IMO), maybe that's related.

Dirvish now fires `BufNew` when a directory is first visited. @Carpetsmoker let me know if you have any better insight or suggestions.
