### ISSUE TITLE
E121: Undefined variable: w:dirvish

### ISSUE THREAD

**Issue by chiphogg** [justinmk/vim-dirvish#24]
Since installing dirvish, I noticed that sometimes (but not always) vim would spit out an angry red storm of messages when I exit.  I managed to get lucky by running `gvim -V9vimlog` and getting the errors to come.  Among other issues, I found this:

```
E121: Undefined variable: w:dirvish
E116: Invalid arguments for function has_key(w:dirvish, '_w_cocu')
E15: Invalid expression: has('conceal') && has_key(w:dirvish, '_w_cocu')
```

My best guess for how to reproduce this uses tpope/vim-fugitive.

1. Change a file in a git repo, and save it.
2. Run `:Gstatus`, select that file, and hit `D` to diff it.
3. Make sure you're in the `fugitive:///`window (i.e., the left one).
4. `:qa`

I think you can fix this by replacing [this line](https://github.com/justinmk/vim-dirvish/blob/80e9bab2fc230ace304b23225c74e4010ea3f319/autoload/dirvish.vim#L172):

```vim
  if has('conceal') && has_key(w:dirvish, '_w_cocu')
```

with this one:

```vim
  if has('conceal') && has_key(w:, 'dirvish') && has_key(w:dirvish, '_w_cocu')
```

I am not sure whether this indicates any deeper issues (fundamental assumptions being violated, etc.) since I don't have any understanding of the codebase.  But this makes the angry redness go away as far as I can tell.

**Comment by justinmk** [comment]
Thanks!

**Comment by justinmk** [comment]
> I am not sure whether this indicates any deeper issues (fundamental assumptions being violated, etc.) 

Nah, the check should be there. I had brazenly concluded that I had covered enough cases such that the absence of `w:dirvish` was worthy of an error. But on further thought, it's not reliable. `BufLeave` can happen in any window, and there could be many scenarios where we didn't get a chance to set up `w:dirvish` properly. It's not worth an error because the functionality is only a best-effort attempt to restore window-local settings (this wasn't always the case).
