### ISSUE TITLE
Opening multiple directories with -p, -o, or -O doesn't work

### ISSUE THREAD

**Issue by Carpetsmoker** [justinmk/vim-dirvish#30]
$ vim / /etc

This works, I can use `:n` to go to the next buffer. However, this gives an error:

    $ vim -p / /etc
    Error detected while processing function dirvish#open..<SNR>55_do_open..<SNR>55_buf_render
    ..<SNR>55_win_do..<SNR>55_tab_win_do:
    line    5:
    E121: Undefined variable: w:dirvish

After continuing I get an empty buffer. Using `gt` to go to the second tab shows the `/` directory (and not `/etc`, like I would expect).

Using `vim -o / /etc` or `vim -O / /etc` also doesn't work, albeit with slightly different errors and none of the buffers get populated. Switching windows with `<C-w>w` gives me a `Undefined variable: w:dirvish
` every time.

**Comment by justinmk** [comment]
Hmm. Looking into this now.

**Comment by justinmk** [comment]
Mostly fixed. There's a minor issue with `-o`/`-O`: the extra windows will be empty until you visit them (netrw has the same issue, and actually seems to require an extra visit). This is because `BufEnter` (and neither `BufAdd`, for that matter) is fired only for the first buffer.

Thanks for reporting!

**Comment by Carpetsmoker** [comment]
:+1:
