### ISSUE TITLE
Does not quit on intro message

### ISSUE THREAD

**Issue by tsuflux** [justinmk/vim-dirvish#41]
When I open dirvish just after starting vim pressing `q` to close it again has no effect.

**Comment by justinmk** [comment]
There's no where for it to go to, because there are no other buffers.

We could add logic to... create a new buffer, or something--but why?

**Comment by tsuflux** [comment]
Well, it just feels inconsistent that pressing `q` after changing directories back and forth will open an empty buffer even though I didn't open a file in the mean time. And on the other side pressing `q` without having changed directories beforehand won't open a new buffer.

**Comment by justinmk** [comment]
@tsuflux You're right, and I agree. Dirvish isn't doing anything to create that new, blank buffer which suddenly becomes available after navigating. It's just an accident of how Vim works. In this case adding code to _create_ a new buffer in order to match the behavior of the post-navigation case, is unattractive.

**Comment by justinmk** [comment]
@tsuflux This is fixed now.
