### ISSUE TITLE
Reload mapping

### ISSUE THREAD

**Issue by Konfekt** [justinmk/vim-dirvish#50]
Would Ctrl-L not fit better than R as a mapping to reload the directory? Of course, conserving :redraw.

**Comment by justinmk** [comment]
I've considered throwing in `:edit` to CTRL-L for my own personal config. The problem is, if you only want to "clear highlight"/redraw the screen, having to consider whether one is ready to reload the file from disk is not equivalent in its non-destructiveness to "clear highlight/redraw/etc". And even for dirvish, reload may be mildly destructive if one made edits to the buffer for some reason (sometimes it's useful, believe it or not).

Reminder that reload can be remapped trivially:

    nnoremap <buffer><silent> <C-L> :Dirvish %<CR>
