### ISSUE TITLE
<C-o> doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [justinmk/vim-dirvish#7]
I'm not sure if this is intended (i.e., you want users to use `u` or `-`), but here's the issue:
- Open directory: `nvim ~/.nvim`
- Enter subdirectory by pressing `Enter` over it
- Press `<C-o>`, get an error `E19: Mark has invalid line number`
- Press `<C-o>` again , back inside `~/.nvim`

Edit: I should probably mention the expected behavior as you can't read my mind, which is that <C-o> goes back to the directory in 1 step, without error.

**Comment by justinmk** [comment]
`E19` doesn't happen anymore, because dirvish now leaves the buffers around as long as they're needed. CTRL-O kinda works now, but it's by accident since `:keepjumps` is used liberally. Initially a goal was to avoid polluting the jumplist totally, but doesn't seem so important now. Maybe `:keepjumps` should be avoided in certain cases.

**Comment by fourjay** [comment]
I've overrode the default ``-`` in dirvish for this reason, to ``nmap - m'<bar><Plug>(dirvish_up)``
My (mis) use case, I sometimes fat finger a ``-`` without entering an insert. When that happens I'd normally just ``<C-O>`` to get back where I was, but without a jumplist mark I'm returned to a previous place :-(

**Comment by justinmk** [comment]
Does `q` not do what you want?

**Comment by fourjay** [comment]
I'd not tried (nor thought to). It does.
My muscle memory expects ``<C-O>`` to work :-)

**Comment by justinmk** [comment]
`q` also takes great care to restore the alternate buffer. Might just do a temporary remap to it for Ctrl-O.
